/**
 * MANUSCRIPT ENGINE — the paper, written now, with the numbers left as holes.
 *
 * Everything that does not depend on the result is already written: background,
 * the gap, methods, the analysis plan, the limitations. Everything that does
 * depend on the result is interpolated from `AnalysisResult` at render time. As
 * data arrives the manuscript updates itself; nobody retypes a number, and no
 * number in the text can drift from the number in the table.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY THE RESULTS SECTION IS DIRECTION-AGNOSTIC.
 *
 * The discussion is written to hold whichever way the effect falls, and the
 * renderer picks the branch from the data — it never asserts a direction the
 * numbers do not support. This is not a stylistic choice. A manuscript drafted
 * around a hoped-for finding is how outcome-reporting bias happens, and with
 * the author also owning the product being evaluated it is the first thing a
 * reviewer will look for.
 *
 * The pre-registered primary outcome is fixed here in code BEFORE recruitment,
 * so it cannot be quietly swapped for whatever turns out significant.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * THE SYNTHETIC STAMP IS NOT OPTIONAL. Rendering from simulated data marks
 * every page. A fabricated effect size that escaped into a grant application or
 * an investor deck would be misconduct, so the stamp is applied by the renderer
 * rather than left to the caller to remember.
 */

import type { AnalysisResult } from './analysis'

export interface ManuscriptOptions {
  /** True when the input came from the mock generator. Stamps every page. */
  synthetic?: boolean
  title?: string
}

const pct = (n: number) => (n * 100).toFixed(1)
const ci = (c: [number, number]) => `${pct(c[0])}–${pct(c[1])}`

/**
 * PRE-REGISTERED PRIMARY OUTCOME. Fixed before recruitment. Changing this after
 * seeing data is outcome switching, and the constant lives here so that any
 * such change is a visible commit rather than an edit to a sentence.
 */
export const PRIMARY_OUTCOME =
  'Participant-reported next-day symptom exacerbation (yes/no), captured by the ' +
  'in-app check-in 12–36 hours after each training session.'

export const PRIMARY_EXPOSURE =
  'Seconds spent above the prescribed sub-symptom heart-rate band during the ' +
  'session, from continuous sensor-verified heart-rate recording.'

export function renderManuscript(r: AnalysisResult, opts: ManuscriptOptions = {}): string {
  const stamp = opts.synthetic
    ? '> **SYNTHETIC DATA — NOT A RESULT.** Every figure below was generated by\n' +
      '> `scripts/research-mock-cohort.mts` to exercise the analysis pipeline and\n' +
      '> size the study. No participant was involved. These numbers must never be\n' +
      '> cited, presented, or reused in any grant, pitch or publication.\n\n'
    : ''

  const inBand = r.exposure[0]
  const longest = r.exposure[r.exposure.length - 1]
  const underpowered = r.cohort.participants < r.power.participants

  // Direction is READ FROM THE DATA, never assumed. Both branches are written.
  const signal =
    longest.sessions > 0 && inBand.sessions > 0 && longest.flareRate > inBand.flareRate * 1.5
      ? 'gradient'
      : longest.sessions > 0 && inBand.sessions > 0 && longest.flareRate <= inBand.flareRate * 1.2
        ? 'null'
        : 'indeterminate'

  return `${stamp}# ${opts.title ?? 'Delivered versus prescribed exercise dose in sub-symptom threshold aerobic rehabilitation after concussion: a prospective observational cohort'}

## Abstract

**Background.** Sub-symptom threshold aerobic exercise (SSTAE) is first-line
treatment for concussion. Prescriptions are anchored to a heart-rate threshold
measured on a graded treadmill test, and patients are instructed to remain below
a band derived from it. The instruction assumes that exceeding the band provokes
symptom exacerbation, but that assumption rests on prescribed dose: almost no
study has measured what patients actually did.

**Objective.** To quantify the relationship between time spent above the
prescribed band and next-day symptom exacerbation, and to determine whether a
tolerable excursion threshold exists.

**Methods.** Prospective observational cohort of adults and adolescents
undergoing clinician-supervised SSTAE. Heart rate was recorded continuously from
a paired sensor; sessions entered the analysis only where at least
${80}% of readings were sensor-verified. ${PRIMARY_OUTCOME}

**Results.** ${r.cohort.participants} participants contributed
${r.cohort.sessions} sessions (median ${r.cohort.sessionsPerParticipant.toFixed(1)}
per participant; median ${r.cohort.medianDaysSinceInjury ?? 'n/a'} days
post-injury at entry). ${r.set.includedSessions} sessions met the analysis
criteria. Next-day exacerbation followed ${pct(inBand.flareRate)}% of sessions
completed entirely within band (95% CI ${ci(inBand.ci95)}) and
${pct(longest.flareRate)}% of sessions with more than five minutes above band
(95% CI ${ci(longest.ci95)}).

**Conclusions.** ${
    signal === 'gradient'
      ? 'Time above the prescribed band was associated with next-day exacerbation in a graded fashion, supporting the band as a clinically meaningful boundary and providing the first estimate of its dose-response.'
      : signal === 'null'
        ? 'Brief excursions above the prescribed band were not associated with a meaningful increase in next-day exacerbation, suggesting that current prescribing may be more restrictive than the evidence requires.'
        : 'The direction of association could not be established at this sample size; the cohort continues to recruit.'
  }

---

## 1. Background

Concussion management has moved decisively from rest to early aerobic activity.
The Amsterdam International Consensus (2023) places sub-symptom threshold
aerobic exercise as first-line treatment rather than an adjunct, following
randomised evidence that early prescribed exercise shortens recovery.

The prescription itself is derived from a graded treadmill test: exercise is
increased until symptoms rise by a defined margin, the heart rate at that point
is taken as the threshold, and training is prescribed at a fraction of it. The
patient is then told not to exceed the resulting band.

**That last instruction is convention rather than measurement.** It follows
naturally from the logic of the threshold, and it is clinically prudent, but the
literature that established SSTAE reports *prescribed* dose — what the clinician
wrote down. Whether patients stayed within the band, and what happened when they
did not, has largely gone unrecorded, because measuring it requires continuous
heart rate during unsupervised sessions plus a systematic next-day follow-up.

### 1.1 The gap

Three things follow from prescribing a boundary whose consequences are unknown:

1. **The boundary may be too tight.** If brief excursions are harmless, the band
   imposes avoidable caution on an intervention whose benefit is dose-related.
2. **It may be too loose in places.** A single tolerable-seeming excursion late
   in a session may matter more than an equivalent one early.
3. **Adherence is unmeasured, so trials are unblinded to their own exposure.**
   Where delivered dose is unknown, a null trial cannot distinguish an
   ineffective prescription from an undelivered one.

### 1.2 Objective

To measure delivered dose against next-day symptom response, and to establish
whether a tolerable excursion budget exists that could be stated to patients.

---

## 2. Methods

### 2.1 Design and setting

Prospective observational cohort embedded in routine clinical care across
participating clinics. No treatment was assigned by the study: prescriptions
were made by the treating clinician on clinical grounds, and the cohort observes
what followed.

### 2.2 Participants

Adolescents and adults (≥13 years) prescribed SSTAE following concussion, who
consented to research use of their de-identified session data. Post-exertional
malaise, screened at intake, is an exclusion from exertion prescription in the
platform and therefore from this cohort.

### 2.3 Exposure

${PRIMARY_EXPOSURE}

Heart rate was sampled continuously from a paired sensor. Each reading is
recorded as sensor-verified or manually entered, and **sessions below
${80}% verified readings were excluded**, because a typed heart rate cannot
evidence time-above-band.

### 2.4 Outcome

${PRIMARY_OUTCOME}

A missing check-in is treated as **unobserved, not negative**. Imputing absent
check-ins as "no exacerbation" would bias the estimate toward the null, and is
the most available error in this design.

### 2.5 Covariates

Days since injury (the dominant covariate in concussion recovery), age band,
sex, and session index within episode.

### 2.6 Statistical analysis

The primary analysis is a **mixed-effects logistic regression** of next-day
exacerbation on seconds-above-band, with a participant-level random intercept.

Sessions are nested within participant, and participants differ substantially in
baseline propensity to flare. Pooling sessions as independent observations
inflates precision and is the most likely route to a spurious finding in this
dataset; the random intercept absorbs that clustering. Descriptive proportions
below are reported with Wilson intervals for transparency and are **not** the
primary inference.

### 2.7 Sample size

To detect a doubling of the in-band exacerbation rate at 80% power and
α = 0.05: ${r.power.naiveSessions} sessions assuming independence, inflated by a
design effect of ${r.power.designEffect.toFixed(2)} (ICC 0.15,
${r.cohort.sessionsPerParticipant.toFixed(0)} sessions per participant) to
${r.power.effectiveSessions} sessions — approximately
**${r.power.participants} participants**.

---

## 3. Results

### 3.1 Cohort

${r.cohort.participants} participants contributed ${r.cohort.sessions} sessions.
Median ${r.cohort.sessionsPerParticipant.toFixed(1)} sessions per participant;
median ${r.cohort.medianDaysSinceInjury ?? 'n/a'} days post-injury at entry.

| Age band | n |
|---|---|
${Object.entries(r.cohort.ageBands).map(([k, v]) => `| ${k} | ${v} |`).join('\n')}

| Sex | n |
|---|---|
${Object.entries(r.cohort.sexes).map(([k, v]) => `| ${k} | ${v} |`).join('\n')}

### 3.2 Analysis set

Of ${r.cohort.sessions} sessions, ${r.set.includedSessions} entered the primary
analysis. Excluded: ${r.set.excludedNoCheckin} with no next-day check-in,
${r.set.excludedUnverified} below the verification threshold,
${r.set.excludedNoZoneData} without time-in-zone data.

### 3.3 Next-day exacerbation by excursion

| Time above band | Sessions | Participants | Exacerbations | Rate | 95% CI |
|---|---|---|---|---|---|
${r.exposure.map((s) => `| ${s.label} | ${s.sessions} | ${s.participants} | ${s.flares} | ${pct(s.flareRate)}% | ${ci(s.ci95)} |`).join('\n')}

---

## 4. Discussion

${
  signal === 'gradient'
    ? `Exacerbation risk rose with time above the prescribed band. This is the first
quantification of a boundary that has been prescribed on reasoning rather than
measurement, and it supports current practice while making the instruction
specific: the relevant quantity is duration of excursion, not whether the band
was ever touched.`
    : signal === 'null'
      ? `Brief excursions were not associated with a meaningful increase in next-day
exacerbation. If replicated, this argues that the current instruction is more
restrictive than the data support. That matters clinically: a prescription
patients experience as fragile is one they abandon, and the benefit of SSTAE is
dose-related. A tolerance stated in minutes rather than an absolute ceiling may
improve delivered dose without increasing symptom burden.`
      : `At this sample size the direction of association is not established. The
descriptive pattern is reported without interpretation; recruitment continues.`
}

### 4.1 Strengths

Delivered dose was measured rather than assumed, with a verification standard
that excludes self-reported heart rate. Follow-up is systematic rather than
retrospective, and the analysis set is defined prospectively.

### 4.2 Limitations

Observational: prescriptions were clinical decisions, so excursions may mark
patients who felt well enough to push, confounding exposure with recovery.
Next-day exacerbation is participant-reported and unblinded. Clinics
participating in this cohort are self-selected toward structured concussion
care. ${underpowered ? `**This analysis is below the pre-specified sample size of ${r.power.participants} participants and is reported as an interim description only.**` : ''}

### 4.3 Conflict of interest

The platform used to collect these data is developed and commercialised by an
author. This is a material conflict. Mitigations: the primary outcome and
analysis were pre-specified before recruitment; the analysis is executed by an
independent statistician; participating clinicians who contributed data are
co-authors with the standing to dissent; and the de-identified analysis dataset
is available for independent re-analysis.

---

## 5. Data availability

De-identified session-level data supporting the findings are available on
request. The dataset carries no clinic identifier, no patient identifier, and no
session timestamp — participants are represented by a random pseudonym that
cannot be reversed by the contributing clinic.

---

*${r.clusterWarning}*
`
}
