/**
 * SST report PDF RENDERER — the same `ReportContent` the HTML renderer
 * consumes, laid out as an A4 jsPDF (the house PDF stack: certificates, tax
 * invoices, the bespoke GP report). One renderer for every skin, exactly like
 * render.ts — a new skin never touches this file.
 *
 * WHY IT EXISTS (owner, 2026-08-11 pre-MSCC): the hub's document buttons
 * opened print-ready HTML in a tab and stopped — no way to actually SEND the
 * form anywhere. This renderer powers both `?format=pdf` on the report route
 * (download) and the report-email endpoint (PDF attachment).
 *
 * Pure function, no I/O. Mirrors render.ts options so the two outputs carry
 * identical letterhead, banners and watermarks — a DEMO watermark must
 * survive into the attachment exactly as it survives into print.
 */
import { jsPDF } from 'jspdf'
import type { ReportContent } from './skins'
import type { RenderReportOptions } from './render'

const TEAL: [number, number, number] = [13, 115, 119]
const INK: [number, number, number] = [30, 41, 59]
const SLATE: [number, number, number] = [100, 116, 139]
const AMBER: [number, number, number] = [180, 83, 9]
const LINE: [number, number, number] = [226, 232, 240]

const PAGE_W = 210
const PAGE_H = 297
const M = 18 // margin, mm
const MAX_W = PAGE_W - M * 2
const BOTTOM = PAGE_H - 24 // keep clear of the footer band

export function renderReportContentToPdf(
  content: ReportContent,
  opts: RenderReportOptions = {},
): ArrayBuffer {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  let y = M

  const watermark = () => {
    if (!opts.draftBanner) return
    doc.saveGraphicsState()
    // @ts-expect-error GState exists at runtime; typings lag
    doc.setGState(new doc.GState({ opacity: 0.07 }))
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(72)
    doc.setTextColor(...AMBER)
    doc.text(opts.watermarkText ?? 'DRAFT', PAGE_W / 2, PAGE_H / 2, {
      align: 'center',
      angle: 32,
    })
    doc.restoreGraphicsState()
  }

  const newPage = () => {
    doc.addPage()
    watermark()
    y = M
  }
  const ensure = (needed: number) => {
    if (y + needed > BOTTOM) newPage()
  }
  // jsPDF's built-in fonts are WinAnsi — a glyph outside it (Δ, ≥, ✓) renders
  // as garbage AND corrupts the line's spacing. Map the ones our skins use;
  // strip anything else non-encodable rather than print mojibake.
  const sanitize = (s: string): string =>
    s
      .replace(/Δ/g, 'delta-')
      .replace(/≥/g, '>=')
      .replace(/≤/g, '<=')
      .replace(/→/g, '->')
      .replace(/←/g, '<-')
      .replace(/✓/g, '[y]')
      // eslint-disable-next-line no-control-regex
      .replace(/[^\x00-\xFF]/g, (ch) => ('–—‘’“”·…€'.includes(ch) ? ch : '?'))
  /**
   * Set the FULL font state, then wrap. Measuring in one font and rendering in
   * another clipped lines at the right margin (bold-metrics measure vs courier
   * render) — the font that measures MUST be the font that draws.
   */
  const fit = (
    text: string,
    size: number,
    width = MAX_W,
    family: 'helvetica' | 'courier' = 'helvetica',
    style: 'normal' | 'bold' = 'normal',
  ): string[] => {
    doc.setFont(family, style)
    doc.setFontSize(size)
    return doc.splitTextToSize(sanitize(text), width) as string[]
  }

  watermark()

  // ── banner (demo / trial) ───────────────────────────────────────────────
  if (opts.draftBanner) {
    const lines = fit(opts.draftBanner, 8.5, MAX_W - 8, 'helvetica', 'bold')
    const h = lines.length * 4 + 6
    doc.setFillColor(254, 243, 199)
    doc.setDrawColor(...AMBER)
    doc.setLineWidth(0.4)
    doc.roundedRect(M, y, MAX_W, h, 1.5, 1.5, 'FD')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8.5)
    doc.setTextColor(124, 45, 18)
    doc.text(lines, PAGE_W / 2, y + 5, { align: 'center' })
    y += h + 6
  }

  // ── title + meta + letterhead ───────────────────────────────────────────
  doc.setTextColor(15, 23, 42)
  for (const line of fit(content.title, 15, MAX_W, 'helvetica', 'bold')) {
    ensure(7)
    doc.text(line, M, y)
    y += 6.5
  }
  doc.setTextColor(...SLATE)
  const generated =
    opts.generatedOn ??
    new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'short', year: 'numeric' })
  const metaBits = [opts.clinicName, `Report generated ${generated}`, 'Generated by SST Trainer · Concussion Education Australia']
    .filter(Boolean)
    .join('  ·  ')
  for (const line of fit(metaBits, 8.5)) {
    doc.text(line, M, y)
    y += 4
  }
  const lh = opts.letterhead
  const lhParts = lh
    ? [lh.practitioner, lh.ahpra ? `AHPRA ${lh.ahpra}` : '', lh.provider ? `Provider no. ${lh.provider}` : '', lh.address, lh.phone].filter(
        (x): x is string => Boolean(x && x.trim()),
      )
    : []
  if (lhParts.length) {
    for (const line of fit(lhParts.join('  ·  '), 8.5)) {
      doc.text(line, M, y)
      y += 4
    }
  }
  y += 3

  // ── sections ────────────────────────────────────────────────────────────
  for (const section of content.sections) {
    ensure(14)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10.5)
    const audit = section.kind === 'audit' || section.kind === 'trajectory'
    doc.setTextColor(...(audit ? TEAL : INK))
    doc.text(sanitize(section.heading), M, y + 4)
    doc.setDrawColor(...LINE)
    doc.setLineWidth(0.25)
    doc.line(M, y + 5.5, PAGE_W - M, y + 5.5)
    y += 9.5

    doc.setTextColor(...INK)
    for (const para of section.body ?? []) {
      for (const line of fit(para, 9.5)) {
        ensure(4.5)
        doc.text(line, M, y)
        y += 4.3
      }
      y += 1.5
    }

    const fields = section.fields ?? []
    if (fields.length) {
      const labelW = 58
      const valueW = MAX_W - labelW - 6
      for (const f of fields) {
        const valueLines = fit(f.value, audit ? 8.4 : 9, valueW, audit ? 'courier' : 'helvetica')
        const labelLines = fit(f.label, 9, labelW - 2, 'helvetica', 'bold')
        const rowH = Math.max(valueLines.length, labelLines.length) * 4.1 + 2.4
        ensure(rowH + 1)
        doc.setDrawColor(...LINE)
        doc.setLineWidth(0.2)
        doc.line(M, y + rowH - 1, PAGE_W - M, y + rowH - 1)
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(9)
        doc.setTextColor(51, 65, 85)
        doc.text(labelLines, M, y + 2.4)
        doc.setFont(audit ? 'courier' : 'helvetica', 'normal')
        doc.setFontSize(audit ? 8.4 : 9)
        doc.setTextColor(...INK)
        doc.text(valueLines, M + labelW + 6, y + 2.4)
        y += rowH + 0.6
      }
      y += 2
    }
    y += 1.5
  }

  // ── signature + footer ──────────────────────────────────────────────────
  ensure(20)
  y += 8
  doc.setDrawColor(148, 163, 184)
  doc.setLineWidth(0.3)
  doc.line(M, y, M + 90, y)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.setTextColor(71, 85, 105)
  doc.text('Supervising clinician — name, signature, date', M, y + 4)

  const footer = `Generated by SST Trainer (Concussion Education Australia) from clinic-supervised program data. Decision-support only — this report does not constitute a diagnosis, prognosis or clearance; the supervising clinician reviews and signs before transmission. Heart-rate values marked verified were captured from a connected sensor; manual or camera entries are never presented as verified.${opts.footerNote ? ` ${opts.footerNote}` : ''} · portal.concussion-education-australia.com/clinics`
  const pages = doc.getNumberOfPages()
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setDrawColor(...TEAL)
    doc.setLineWidth(0.7)
    doc.line(M, PAGE_H - 18, PAGE_W - M, PAGE_H - 18)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(6.8)
    doc.setTextColor(...SLATE)
    doc.text(doc.splitTextToSize(footer, MAX_W) as string[], M, PAGE_H - 14.5)
  }

  return doc.output('arraybuffer') as ArrayBuffer
}
