/**
 * SST → PMS delivery — the LOOP-CLOSER.
 *
 * This is the module that makes SST the structural inverse of ZEDOC's #1 failure
 * ("standalone, no PMS integration — the killer"). The SST report never lives in
 * a separate portal the clinician has to log into: at episode end (or any review
 * point) the structured report is written straight into the patient's record in
 * the PMS they already use — as a clinical NOTE, and optionally the rendered PDF
 * as a filed ATTACHMENT.
 *
 * DESIGN: talks ONLY to the `PmsAdapter` seam — it has no idea whether the target
 * is Cliniko or Gensolve. A new PMS needs zero change here. Delivery is
 * flag-gated and fail-safe: with no config / flag off it returns a `skipped`
 * result and NEVER throws, so a missing key can never break a caller.
 */

import type { PmsAdapter, PmsAdapterConfig, PmsKind, PmsWriteResult } from './adapter'
import { getAdapter } from './adapter'
import type { ReportContent } from '../reports/skins'

/** Flatten a structured report into a clean plain-text note body for the PMS. */
export function reportContentToNoteText(content: ReportContent): string {
  const lines: string[] = [content.title, '']
  for (const section of content.sections) {
    lines.push(section.heading.toUpperCase())
    for (const p of section.body ?? []) lines.push(p)
    for (const f of section.fields ?? []) lines.push(`  ${f.label}: ${f.value}`)
    lines.push('')
  }
  lines.push(
    'Generated by SST Trainer (Concussion Education Australia) from clinic-supervised program data. ' +
      'Decision-support only — not a diagnosis, prognosis or clearance. The supervising clinician reviews and signs before use.',
  )
  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trim()
}

export interface DeliverReportInput {
  adapter: PmsAdapter
  /** PMS patient/client id the note + attachment file against. */
  patientId: string
  /** The already-rendered report structure (caller picks the jurisdiction skin). */
  content: ReportContent
  /** ISO 8601 time the clinical event occurred (defaults to caller-supplied now). */
  occurredAt: string
  /** Optional rendered PDF to file as an attachment alongside the note. */
  pdf?: { filename: string; bytes: Uint8Array }
}

export interface DeliverReportResult {
  /** true when at least the note was written. */
  ok: boolean
  note: PmsWriteResult
  /** present only when a pdf was supplied. */
  attachment?: PmsWriteResult
}

/**
 * Write a report into the PMS: a clinical note always, the PDF attachment when
 * supplied. Never throws — adapter methods already return results, and a failed
 * attachment does not fail the note (the note is the load-bearing record).
 */
export async function deliverReport(input: DeliverReportInput): Promise<DeliverReportResult> {
  const { adapter, patientId, content, occurredAt, pdf } = input
  const note = await adapter.writeNote(patientId, {
    title: content.title,
    body: reportContentToNoteText(content),
    occurredAt,
  })
  let attachment: PmsWriteResult | undefined
  if (pdf) {
    attachment = await adapter.attachPdf(patientId, { filename: pdf.filename, bytes: pdf.bytes })
  }
  return { ok: note.ok, note, attachment }
}

// ── configuration (env-gated, dormant until a real key + flag) ────────────────

/**
 * True only when write-back is explicitly enabled. Default OFF: the integration
 * ships dormant so it can be reviewed / demoed without any live PMS traffic.
 */
export function pmsWritebackEnabled(): boolean {
  return process.env.PMS_WRITEBACK_ENABLED === 'true'
}

/**
 * Build an adapter config from environment for a given PMS, or null when the
 * required key is absent. Keys are per-PMS so a clinic can connect one without
 * the other. NEVER hard-codes a credential.
 */
export function getPmsConfigFromEnv(kind: PmsKind): PmsAdapterConfig | null {
  const userAgent = process.env.PMS_USER_AGENT || undefined
  if (kind === 'cliniko') {
    const apiKey = process.env.CLINIKO_API_KEY?.trim()
    if (!apiKey) return null
    return { apiKey, userAgent }
  }
  if (kind === 'nookal') {
    const apiKey = process.env.NOOKAL_API_KEY?.trim()
    if (!apiKey) return null
    const practitionerId = process.env.NOOKAL_PRACTITIONER_ID?.trim()
    return { apiKey, userAgent, creds: practitionerId ? { practitionerId } : undefined }
  }
  // gensolve
  const apiKey = process.env.GENSOLVE_API_KEY?.trim()
  if (!apiKey) return null
  const practiceId = process.env.GENSOLVE_PRACTICE_ID?.trim()
  return { apiKey, userAgent, creds: practiceId ? { practiceId } : undefined }
}

/**
 * Resolve a configured, enabled adapter for a PMS, or null when write-back is
 * disabled or unconfigured. The single entry point a route/cron would call — it
 * cannot return a live adapter unless BOTH the flag is on AND a key is present.
 */
export function resolvePmsAdapter(kind: PmsKind): PmsAdapter | null {
  if (!pmsWritebackEnabled()) return null
  const config = getPmsConfigFromEnv(kind)
  if (!config) return null
  return getAdapter(kind, config)
}
